### ISSUE TITLE
boost/gil/image.hpp in Boost 1.54.0 won't compile with XCode 5.0.1

### ISSUE THREAD

**Issue by sean-parent** [stlab/adobe_platform_libraries#1]
Change "-1" to "-1UL" to patch. But boost/gil doesn't look like it is being maintained and should be removed - perhaps as part of Begin rewrite.

**Comment by mloskot** [comment]
Please, consider submitting the patch to the upstream at https://github.com/boostorg/gil
After some quiet years, Boost.GIL is being maintained now.

**Comment by camio** [comment]
This issue is eight years old so withdrawing. Please reopen if this is still relevant/required.
