### ISSUE TITLE
Update projects to handle deeper constexpr and template recursion

### ISSUE THREAD

**Issue by fosterbrereton** [stlab/adobe_platform_libraries#4]
Begin is failing to build because of the name_t integration to ASL. The error is that the constexpr depth and the template depth need to be expanded from their compiler defaults. Under bjam we do this with:

```
-fconstexpr-depth=1024 -ftemplate-depth=1024
```

We'll need to do something similar for the Begin project.

**Comment by camio** [comment]
This issue is 9 years old so withdrawing. If still relevant, please feel free to reopen.
