### ISSUE TITLE
Usage of Placeable concept in Eve layout code

### ISSUE THREAD

**Issue by ilelann** [stlab/adobe_platform_libraries#6]
Some context : Linux Support  https://github.com/stlab/adobe_source_libraries/issues/33

In my work to implement a [GTK backend](https://github.com/ilelann/adobe_platform_libraries/tree/gtk)  I completely skipped for now the placeable concept. I provided [no-op measure/place method](https://github.com/ilelann/adobe_platform_libraries/blob/gtk/backend/template/adobe/future/widgets/templates/widget_base.hpp#L23).
It works, with bugs to solve, but layout is skipped and thus dialogs sometimes look ugly.
I see two options to fix this :
- implement placeable 
- skip eve layout code and instead forward layout information directly to GTK 

From what I saw in windows backend, it takes quite an effort, and many magic numbers, to implement measure for each widget. See [this](https://github.com/stlab/adobe_platform_libraries/blob/master/windows/adobe/future/widgets/sources/platform_label.cpp#L85)  or [this](https://github.com/stlab/adobe_platform_libraries/blob/master/windows/adobe/future/widgets/sources/platform_group.cpp#L102) for example.

I will try to find out how to write similar code for GTK but I have to admit that, lazy as I am, forwarding to backend seems a far better idea at this point. I haven't really dug how to do that, but I guess that would be something like introducing a "Layoutable" concept, used in an alternate eve.cpp file. 

Thoughts ? Am I missing something about placeable concept usage in Eve ?

Regards,
Ivan

**Comment by sean-parent** [comment]
The minimum information you need to provide for Eve layout is the ideal width/height of an object. If you framework provides that, it should be pretty easy to plug together. With more information, Eve can do better. Alternatively, you can map the layout attributes to whatever GTK provides and let it do the job.

**Comment by ilelann** [comment]
OK. Taking a closer look, I might have been too pessimist on this.
Will test a combination of [gtk_widget_get_preferred_size](https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-get-preferred-size) and [GtkLayout](https://developer.gnome.org/gtk3/stable/GtkLayout.html) as container.

**Comment by camio** [comment]
Withdrawing because this work on GTK+Eve support seems to have been abandoned. Please feel free to reopen if this is still relevant.
